openapi: '3.0.2'
info:
  title: Orders API
  description: API for CRUD orders use Golang Framework Gin and GORM Postgre
  version: '1.0'
servers:
  - url: https://localhost:3000
components:
  schemas:
    Item: 
      type: object
      properties:
        item_id:
          type: number
        item_code:
          type: string
        description:
          type: string
        quantity:
          type: number
    ItemWithoutID: 
      type: object
      properties:
        item_code:
          type: string
        description:
          type: string
        quantity:
          type: number
    ResponseGetCreateOrder:
      type: object
      properties:
        order_id:
          type: number
        customer_name:
          type: string
        ordered_at:
          type: string
        items:
          type: array
          items: 
            $ref: '#/components/schemas/Item'
    RequestCreateOrder:
      type: object
      properties:
        customer_name:
          type: string
        ordered_at:
          type: string
        items:
          type: array
          items: 
            $ref: '#/components/schemas/ItemWithoutID'
    ResponseError:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        error:
          type: string
paths:
  /orders:
    get:
      tags: 
        - orders
      description: List of order with items
      summary: List of order with items
      responses:
        '200':
          description: Success get all order with items
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResponseGetCreateOrder'
        '400':
          description: Failed get all order with items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
    post:
      tags: 
        - orders
      description: Create new order
      summary: Create new order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCreateOrder'
      responses:
        '200':
          description: Success create new order
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResponseGetCreateOrder'
        '400':
          description: Failed create new order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /orders/{orderID}:
    get:
      tags: 
        - orders
      responses:
        '200':
          description: OK
    put:
      tags: 
        - orders
      responses:
        '200':
          description: OK
    delete:
      tags: 
        - orders
      responses:
        '200':
          description: OK