openapi: '3.0.2'
info:
  title: Orders API
  description: API for CRUD orders use Golang Framework Gin and GORM Postgre
  version: '1.0'
servers:
  - url: https://localhost:3000
paths:
  /orders:
    get:
      tags: 
        - "Orders"
      responses:
        '200':
          description: OK
    post:
      tags: 
        - "Orders"
      responses:
        '200':
          description: OK
  /orders/{orderID}:
    get:
      tags: 
        - "Orders"
      responses:
        '200':
          description: OK
    put:
      tags: 
        - "Orders"
      responses:
        '200':
          description: OK
    delete:
      tags: 
        - "Orders"
      responses:
        '200':
          description: OK
  /items:
    get:
      tags: 
        - "Items"
      responses:
        '200':
          description: OK
    post:
      tags: 
        - "Items"
      responses:
        '200':
          description: OK
  /items/{itemID}:
    get:
      tags: 
        - "Items"
      responses:
        '200':
          description: OK
    put:
      tags: 
        - "Items"
      responses:
        '200':
          description: OK
    delete:
      tags: 
        - "Items"
      responses:
        '200':
          description: OK